-- PostgreSQL Script
-- 29.12.2023 20:35
-- Adding items to question entity (Prototype)

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Czerwony trójkątny proporzec umieszczony w części dziobowej statku na wodach śródlądowych oznacza',
        'statek, któremu przysługuje pierwszeństwo przejścia w miejscach, gdzie obowiązuje kolejność przejścia',
        'statek przewożący materiały niebezpieczne',
        'prom na uwięzi',
        'PRZEPISY',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Dwa jachty żaglowe płyną tym samym halsem. Prawo drogi posiada jacht',
        'nawietrzny',
        'będący z prawej strony drugiego',
        'zawietrzny',
        'PRZEPISY',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Mała gala flagowa podnoszona jest',
        'na jachtach w ruchu, płynących na silniku',
        'na jachtach zacumowanych w porcie',
        'na jachtach pod żaglami',
        'PRZEPISY',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Dodatkowe czerwone światło, poruszające się wahadłowo oznacza',
        'statek na kotwicy',
        'statek, który utracił manewrowość',
        'statek zajęty holowaniem',
        'PRZEPISY',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Statek znajdujący się w niebezpieczeństwie wzywa pomocy używając',
        'rakiet lub pocisków wyrzucających jedynie białe rakiety',
        'rakiet lub pocisków wyrzucających czerwone rakiety',
        'rakiet lub pocisków wyrzucających czerwone i białe rakiety',
        'PRZEPISY',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Osoba prowadząca jacht żaglowy o długości kadłuba większej niż 7,5m po śródlądowych drogach wodnych powinna posiadać',
        'patent żeglarski',
        'kartę pływacką i dokumenty jachtu',
        'książeczkę żeglarską lub patent żeglarski',
        'PRZEPISY',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Światło zielone nad białym bez widocznych innych świateł nawigacyjnych na wodach śródlądowych oznacza',
        'prom na uwięzi',
        'statek na kotwicy',
        'tatek o ograniczonej zdolności manewrowej',
        'PRZEPISY',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Obowiązujące przepisy żeglugowe',
        'zabraniają uszkadzania budowli i urządzeń wodnych',
        'nie regulują kwestii związanych z zanieczyszczeniem dróg wodnych',
        'pozwalają na cumowanie do boi farwaterowych',
        'PRZEPISY',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Powtarzające się długie dźwięki oznaczają',
        'zmieniam mój kurs w lewo',
        'wzywam pomocy',
        'mam zamiar zawrócić w prawo',
        'PRZEPISY',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jeżeli 2 jachty spotkają się w główkach portu, to który jacht ma pierwszeństwo',
        'większy jacht',
        'wychodzący',
        'wchodzący',
        'PRZEPISY',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Śluza to',
        'przegroda poprzeczna spiętrzająca wodę',
        'budowla łącząca dwa akweny o różnych poziomach wody',
        'kanał spławny',
        'PODSTAWY_LOCJI',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Szlak żeglowny jest to',
        'oznakowany pas wody o dostatecznej dla żeglugi głębokości i szerokości',
        'każdy akwen, na którym można uprawiać żeglarstwo',
        'każdy akwen niezależnie od jego wielkości i głębokości',
        'PODSTAWY_LOCJI',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Północny znak kardynalny należy omijać',
        'jedynie od strony południa',
        'od północy, zachodu lub wschodu,',
        'od północy - pozostawiając go na południu od siebie.',
        'PODSTAWY_LOCJI',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Południowy znak kardynalny ma kolor',
        'czarny nad żółtym nad czarnym',
        'żółty nad czarnym',
        'żółto-czarny-żółty',
        'PODSTAWY_LOCJI',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'System jednolitego międzynarodowego oznakowania nawigacyjnego nazywa się systemem',
        'SRC',
        'IALA',
        'PADI',
        'PODSTAWY_LOCJI',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Pława kulista w poziome zielono - czerwone pasy oznacza',
        'lewą stronę szlaku żeglownego',
        'przejście szlaku wodnego pod prawym brzegiem',
        'rozgałęzienie szlaku żeglownego',
        'PODSTAWY_LOCJI',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Pława w biało-czerwone pasy ze znakiem szczytowym w kształcie walca oznacza',
        'nakaz przejścia na prawą stronę szlaku żeglownego',
        'znak pływający przy prawym brzegu',
        'znak pływający przy lewym brzegu',
        'PODSTAWY_LOCJI',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Zielona tyka oznacza',
        'granicę akweny zamkniętego',
        'lewą granicę szlaku żeglownego',
        'prawą granicę szlaku żeglownego',
        'PODSTAWY_LOCJI',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Podczas śluzowania cumy zakładamy',
        'nabiegowo',
        'do górnego i dolnego polera jednocześnie na dowolny węzeł cumowniczy',
        'wiążąc do górnego polera na węzeł cumowniczy żeglarski',
        'PODSTAWY_LOCJI',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Kategoria jachtów B - "Pełnomorska" dotyczy jachtów',
        'jednostki zaprojektowane do rejsów po wodach przybrzeżnych, dużych zatokach, w warunkach wiatru o sile do 6°B włącznie i przy fali o wysokości znaczącej do2 m włącznie',
        'jednostki zaprojektowane do rejsów pełnomorskich, w warunkach wiatru o sile do 8°B włącznie i przy fali o wysokości znaczącej do 4 m włącznie',
        'jednostki zaprojektowane do dalekich rejsów, w warunkach wiatru silniejszego niż 8°B i przy fali o wysokości znaczącej przekraczającej 4 m',
        'PODSTAWY_BUDOWY_JACHTOW',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Pomieszczenie kuchenne na jachcie nosi nazwę:',
        'kokpit',
        'kambuz',
        'kingston',
        'PODSTAWY_BUDOWY_JACHTOW',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Urządzenia do służące do prowadzenia cum to',
        'półkluzy',
        'reling',
        'pawęż',
        'PODSTAWY_BUDOWY_JACHTOW',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jakie proporcje oleju silnikowego i benzyny używa się w silnikach 2-suwowych',
        '1:20',
        'nie ma to znaczenia',
        'takie jak zaleca producent, należy sprawdzić w instrukcji silnika',
        'SILNIKI_I_UKLADY_NAPEDOWE',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Przed uruchomieniem silnika chłodzonego wodą należy',
        'sprawdzić czy spodzina silnika zanurzona jest w wodzie',
        'zalać go wodą i uruchomić',
        'uruchomić go na sucho',
        'SILNIKI_I_UKLADY_NAPEDOWE',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Sprawność układu chłodzenia w silniku sprawdzamy w następujący sposób',
        'przykładając dłoń do obudowy silnika',
        'nasłuchując odgłosu pracy silnika',
        'patrząc czy wypływa woda z otworu kontrolnego obiegu wody chłodzącej silnik',
        'SILNIKI_I_UKLADY_NAPEDOWE',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'W trudnych warunkach meteorologicznych grożących wywrotką jachtu osoby przebywającą pod pokładem powinny',
        'przygotować kamizelki ratunkowe do użycia i pozostać pod pokładem',
        'wyjść na pokład i założyć na siebie kamizelki ratunkowe',
        'pozostać pod pokładem',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Człowiek będący w wodzie, któremu rzucono koło ratunkowe',
        'kładzie się na nim',
        'pływa obok trzymając się linki przymocowanej do koła',
        'zakłada koło przez głowę pod ramiona',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Przed rozpoczęciem reanimacji poszkodowanego należy ułożyć',
        'na plecach; na miękkim, sprężystym podłożu',
        'w pozycji bocznej ustalonej',
        'na plecach; na twardym i równym podłożu',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Cumy i szpringi na jachcie',
        'mogą mieć zaciśnięcie węzły i supły',
        'muszą być w dobry stanie bez węzłów i supłów oraz gotowe do użycia',
        'mogą leżeć niezbuchtowane w kokpicie',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Przed przystąpieniem do sztucznego oddychania u osoby nieprzytomnej należy',
        'udrożnić drogi oddechowe',
        'ułożyć na miękkim sprężystym podłożu',
        'ułożyć ofiarę w pozycji bocznej ustalonej',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Do tonącego człowieka podpływamy',
        'z dużą prędkością',
        'z mała prędkością',
        '	na biegu wstecznym',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Podczas wykonywania manewru "człowiek za burtą" należy',
        'cały czas obserwować jego pozycję',
        'skoczyć za nim',
        'pomachać człowiekowi na do widzenia',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Po wystąpieniu poparzenia 1 stopnia należy w pierwszej kolejności',
        'szybko schłodzić ranę',
        'oczyścić ranę z uszkodzonej skóry',
        'osłonić ranę jałowym opatrunkiem',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Co to jest hipotermia',
        'wychłodzenie organizmu',
        'podwyższona temperatura',
        'szok termiczny',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Zmniejszenie utraty ciepła z organizmu możemy uzyskać',
        'stosując odpowiednie ułożenie ciała, zwane pozycją HELP',
        'masując ramiona i uda w określonych odstępach czasu',
        'podając napoje chłodzące',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Osoby nie potrafiące pływać powinny',
        'Mieć założone kamizelki ratunkowe i siedzieć pod pokładem',
        'Muszą być przywiązane do jachtu',
        'Powinny zawsze mieć na sobie kamizelki ratunkowe i unikać siedzenia pod pokładem',
        'WIADOMOSCI_Z_RATOWNICTWA_WODNEGO',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Wiatr określany jako 1° w skali Beauforta to',
        'słaby wiatr',
        'umiarkowany wiatr',
        'powiew',
        'WIADOMOSCI_Z_METEOROLOGII',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Przepływając przy wysokim brzegu, w kierunku którego wiatr wieje prostopadle możemy spodziewać się',
        'blisko brzegu bezpiecznej żeglugi bez zakłoceń',
        'blisko brzegu zmiany kierunku wiatru o 90° i znacznego wzrostu jego siły',
        'lisko brzegu zmiany kierunku wiatru nawet o 180°',
        'WIADOMOSCI_Z_METEOROLOGII',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Długotrwałe opady o niezbyt silnym natężeniu zwiastują chmury',
        'Cirrus i cirrostratus',
        'Cumulus i cumulonimbus',
        'Stratus i Nimbostratus',
        'WIADOMOSCI_Z_METEOROLOGII',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Bryza dzienna to wiatr wiejący',
        'od lądu do wody',
        'od wody do lądu',
        'o zachodzie słońca',
        'WIADOMOSCI_Z_METEOROLOGII',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Zjawisku dyszy na akwenie wodnym z reguły towarzyszy',
        'intensywny opad deszczu',
        'wyładowania atmosferyczne',
        'nagły wzrost siły wiatru',
        'WIADOMOSCI_Z_METEOROLOGII',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Środek ożaglowania żagla trójkątnego znajdziemy na przecięciu',
        'dwusiecznych kątów',
        'środkowych boków',
        'symetralnych boków',
        'TEORIA_ZEGLOWANIA',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Sposoby przesunięcia środka ożaglowania do tyłu na jachcie typu slup to',
        'zrzucenie foka',
        'wyluzowanie grota',
        'nagły wzrost siły wiatru',
        'TEORIA_ZEGLOWANIA',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Kiedy siła przechylająca osiąga najmniejszą wartość',
        'na kursie półwiatr',
        'na kursie bajdewind',
        'na kursie fordewind',
        'TEORIA_ZEGLOWANIA',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jakie działania podejmowane są w celu ochrony wód przed zanieczyszczeniem',
        'Wprowadzanie przepisów regulujących ilość emisji substancji toksycznych do wód',
        'Organizowanie kampanii edukacyjnych dotyczących ochrony środowiska wodnego',
        'Budowa nowych elektrowni wodnych w celu oczyszczania wód',
        'OCHRONA_WOD_PRZED_ZANIECZYSZCZENIEM',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Co to jest Bilans Azotowy i dlaczego jest ważny dla ochrony wód',
        'Bilans Azotowy to ilość azotu wprowadzana do wód minus ilość usuwana z wód. Nadmiar azotu może prowadzić do eutrofizacji wód',
        'Bilans Azotowy to rodzaj statystyki stosowanej w żeglarstwie. Nie ma związku z ochroną wód',
        'Bilans Azotowy dotyczy ilości azotu w powietrzu i nie ma wpływu na ochronę wód',
        'OCHRONA_WOD_PRZED_ZANIECZYSZCZENIEM',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Co oznacza termin "Ścieki Sanitarne" i jakie substancje mogą być w nich obecne',
        'Ścieki Sanitarne to odpady przemysłowe. Mogą zawierać chemikalia i substancje toksyczne',
        'Ścieki Sanitarne to odprowadzane do kanalizacji ścieki z gospodarstw domowych. Mogą zawierać bakterie, resztki żywności i detergenty',
        'Ścieki Sanitarne to wody opadowe zbierane z powierzchni ziemi',
        'OCHRONA_WOD_PRZED_ZANIECZYSZCZENIEM',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jakie są podstawowe pomoce nawigacyjne używane podczas żeglugi na otwartym morzu',
        'Latarnie morskie, boje i sygnalizatory dźwiękowe',
        'Mapy topograficzne i kompas',
        'GPS i radar',
        'POMOCE_NAWIGACYJNE',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jakie są główne rodzaje kompasów stosowanych na statkach',
        'Kompas magnetyczny, gyrokompas i fluxgate kompas',
        'Kompas topograficzny i kompas GPS',
        'Kompas szkolny i kompas laserowy',
        'POMOCE_NAWIGACYJNE',
        'FIRST_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Kto ma obowiązek noszenia kamizelki ratunkowej na pokładzie żaglówki',
        'Tylko dzieci poniżej 21 roku życia',
        'Tylko dzieci poniżej 12 roku życia',
        'Każda osoba na pokładzie, z wyjątkiem załogi',
        'PODSTAWOWE_PRZEPISY_PRAWA',
        'THIRD_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

INSERT INTO wateradventure.questions(id,
                                     content,
                                     first_answer,
                                     second_answer,
                                     third_answer,
                                     category,
                                     correct_answer,
                                     explanation,
                                     image,
                                     created_at,
                                     modified_at)
VALUES (default,
        'Jakie są podstawowe zasady nawigacji na wodach śródlądowych',
        'Jednostki pływające zawsze mają pierwszeństwo. Nie ma konieczności przestrzegania zasad nawigacji',
        'Ustąp pierwszeństwa jednostkom pływającym z prawej strony. Przepływaj blisko brzegu',
        'Ustąp pierwszeństwa jednostkom pływającym z lewej strony.',
        'PODSTAWOWE_PRZEPISY_PRAWA',
        'SECOND_ANSWER',
        '',
        '',
        '2023-12-29 20:16:30.272000',
        '2023-12-29 20:16:30.272000');

