-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 20:29:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Management_infos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Management_infos` (
  `id` BIGINT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id` BIGINT NOT NULL,
  `type` ENUM('kurs_motorowodny', 'kurs_zeglarski') NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE NOT NULL,
  `status` ENUM('zakończony', 'rozpoczęty', 'nierozpoczęty') NOT NULL,
  `Management_infos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Courses_Management_infos1_idx` (`Management_infos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Management_infos1`
    FOREIGN KEY (`Management_infos_id`)
    REFERENCES `mydb`.`Management_infos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participant_Course_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participant_Course_Info` (
  `id` BIGINT NOT NULL,
  `acces_given_at` DATE NOT NULL,
  `is_passed` TINYINT NOT NULL,
  `Course_id` BIGINT NOT NULL,
  `Management_infos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Accesses_Courses1_idx` (`Course_id` ASC) VISIBLE,
  INDEX `fk_Participant_Course_Info_Management_infos1_idx` (`Management_infos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Accesses_Courses1`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`Courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participant_Course_Info_Management_infos1`
    FOREIGN KEY (`Management_infos_id`)
    REFERENCES `mydb`.`Management_infos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participants_Learning_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participants_Learning_History` (
  `id` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Participants` (
  `id` BIGINT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `Accesses_id` BIGINT NOT NULL,
  `Answers_History_id` BIGINT NOT NULL,
  `Management_infos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Accesses_idx` (`Accesses_id` ASC) VISIBLE,
  INDEX `fk_Participants_Participants_Answers_History1_idx` (`Answers_History_id` ASC) VISIBLE,
  INDEX `fk_Participants_Management_infos1_idx` (`Management_infos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Accesses`
    FOREIGN KEY (`Accesses_id`)
    REFERENCES `mydb`.`Participant_Course_Info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_Participants_Answers_History1`
    FOREIGN KEY (`Answers_History_id`)
    REFERENCES `mydb`.`Participants_Learning_History` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participants_Management_infos1`
    FOREIGN KEY (`Management_infos_id`)
    REFERENCES `mydb`.`Management_infos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `id` BIGINT NOT NULL,
  `content` TEXT NOT NULL,
  `first_answer` VARCHAR(45) NOT NULL,
  `second_answer` VARCHAR(45) NOT NULL,
  `third_anser` VARCHAR(45) NOT NULL,
  `section` ENUM('przepisy', 'podstawy_locji') NOT NULL,
  `correct_answer` ENUM('first_answer', 'second_answer', 'third_answer') NOT NULL,
  `explanation` TEXT NULL,
  `image` VARCHAR(45) NULL,
  `Management_infos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Questions_Management_infos1_idx` (`Management_infos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Management_infos1`
    FOREIGN KEY (`Management_infos_id`)
    REFERENCES `mydb`.`Management_infos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `id` BIGINT NOT NULL,
  `type` ENUM('kawalerski', 'panienski') NOT NULL,
  `is_paid` TINYINT NOT NULL,
  `cost` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL,
  `city` ENUM('sopot', 'olecko') NOT NULL,
  `orderer_email` VARCHAR(9) NOT NULL,
  `orderer_first_name` VARCHAR(45) NOT NULL,
  `orderer_last_name` VARCHAR(45) NOT NULL,
  `orderer_phone_number` VARCHAR(45) NOT NULL,
  `Management_infos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Events_Management_infos1_idx` (`Management_infos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Events_Management_infos1`
    FOREIGN KEY (`Management_infos_id`)
    REFERENCES `mydb`.`Management_infos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`General_learning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`General_learning` (
  `id` BIGINT NOT NULL,
  `course_type` ENUM('sternik_motorowodny', 'inny') NOT NULL,
  `questions_answered` INT NOT NULL,
  `correct_answers` INT NOT NULL,
  `Participants_Learning_History_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_General_learning_Participants_Learning_History1_idx` (`Participants_Learning_History_id` ASC) VISIBLE,
  CONSTRAINT `fk_General_learning_Participants_Learning_History1`
    FOREIGN KEY (`Participants_Learning_History_id`)
    REFERENCES `mydb`.`Participants_Learning_History` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category_learning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category_learning` (
  `id` BIGINT NOT NULL,
  `course_type` ENUM('sternik_motorowodny', 'cos_tam') NOT NULL,
  `questions_answered` INT NOT NULL,
  `correct_answers` INT NOT NULL,
  `category` ENUM('xdddd', 'xdddddd') NOT NULL,
  `Participants_Learning_History_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Category_learning_Participants_Learning_History1_idx` (`Participants_Learning_History_id` ASC) VISIBLE,
  CONSTRAINT `fk_Category_learning_Participants_Learning_History1`
    FOREIGN KEY (`Participants_Learning_History_id`)
    REFERENCES `mydb`.`Participants_Learning_History` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trial_exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trial_exam` (
  `id` BIGINT NOT NULL,
  `course_type` ENUM('xddddd', 'xdddd') NOT NULL,
  `total` INT NOT NULL,
  `passed` INT NOT NULL,
  `failed` INT NOT NULL,
  `Participants_Learning_History_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Trial_exam_Participants_Learning_History1_idx` (`Participants_Learning_History_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trial_exam_Participants_Learning_History1`
    FOREIGN KEY (`Participants_Learning_History_id`)
    REFERENCES `mydb`.`Participants_Learning_History` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
